config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # devise_for :accounts
  devise_for :accounts, defaults: { format: :json }, controllers: { registrations: "registrations", sessions: "sessions", passwords: "passwords",confirmations: "confirmations", invitations: "invitations"}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'homepage#index'
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do

      resource :games, only: [] do
        get :game_codeplayers, :demo, :game_history, :get_open_session_list,
            :generate_playlist, :account_setting, :get_series_games, :career_data,
            :get_open_series_list, :get_game_profiles, :authenticate_users,
            :get_index_data, :get_trivia_assets

        post :get_api_authentication_token, :add_new_round, :update_state,
             :current_round, :song_loaded, :active_song, :get_game_data, :solo,
             :start_new_game, :check_game_code, :game_configurations_update,
             :get_leaderboard_data, :close_open_session, :close_open_series,
             :get_series_detail, :get_remote_data, :game_volume_request,
             :skip_and_add_song_current_game, :advance_song_in_game, :launch_appliance,
             :reset_round_score, :player_answers, :reset_game, :game_players,
             :player_playlist, :gifting_component, :pusher_update, :current_points,
             :game_leaderboard, :skip_song_data, :add_feedback, :redeem_index_spiff,
             :active_camp_session,:update_spiff, :get_song_data, :get_songs, :update_setting,
             :get_series_summary, :update_appliance, :trivia_ticket_score, :get_filtered_song_count, :match_mates,
             :mayhem_spinner_update, :send_message

        patch :update_game_after_request
      end

      resources :rounds do
        resources :songs, only: :index
      end
      resource :mirror do
        post :mirror_data, :game_over_data
      end

      resource :player do
        get :players_game, :get_random_name, :series_score, :songs_played
        post :rewards, :send_email_to_players, :check_player_present, :find_scores, :check_player_present_in_last_game,
             :get_demo_data, :resend_email_confirmation, :send_host_answer, :set_playlist, :host_playlists, :redeem_ticket,
             :winner_ticket, :tickets, :send_rewards, :redeem_pick, :unmute_player,:redeem_spiff,:gift_tickets,
             :total_score, :check_player_name, :update_players_picks, :verify_otp
      end

      resource :pages do
        get :shared
        post :feedback
      end

      resources :guestusers
      resources :guesses
      resources :games
      resources :players
      resources :videos
    end
  end

  post '/admin/download_song_data' => 'download#download_song_data', as: :admin_download_song_data
  post '/admin/upload_csv' => 'download#upload_csv'
  post '/admin/upload_playlist_csv' => 'download#upload_playlist_csv'
  post '/admin/player_guess_history' => 'download#player_guess_history', as: :admin_player_guess_history
  post '/admin/all_player_guess_history' => 'download#all_player_guess_history', as: :admin_all_player_guess_history
  post '/admin/all_player_trivia_answers' => 'download#all_player_trivia_answers', as: :admin_all_player_trivia_answers
  post '/admin/download_songs_in_playlist' => 'download#download_songs_in_playlist', as: :admin_download_songs_in_playlist
  post '/admin/download_playlist_song_data' => 'download#download_playlist_song_data', as: :admin_download_playlist_song_data
  get 'admin/songs/:id/get_expanded_data' => 'api/v1/songs#get_expanded_data'
  post '/admin/songs/:id/update_song_custom_data' => 'api/v1/songs#admin_update_song_custom_data', as: :admin_update_song_custom_data
  patch '/admin/songs/:id/update_song' => 'api/v1/songs#admin_update_song', as: :admin_update_song
  get '/dropboxauthorize' => 'dropbox#authorize', :as => :dropbox_auth
  get '/dropbox/auth_callback' => 'dropbox#callback', :as => :dropbox_callback
  get '/admin/videos/:id/start' => 'api/v1/videos#play', as: :admin_video_play
  get '/admin/videos/:id/end' => 'api/v1/videos#end', as: :admin_video_end
  get '/admin/videos/:id/delete_image' => 'api/v1/videos#destroy_image', as: :admin_video_image_delete
  patch '/admin/stripe_sandbox_switch' => 'charges#stripe_sandbox_switch', as: :admin_stripe_sandbox_switch
  get '*path', to: 'homepage#index'
  post '*path', to: 'homepage#index'
  post '/', to: 'homepage#index'
  match '*path', to: 'homepage#index', via: :options
  match '/', to: 'homepage#index', via: :options

end

app/controllers/api/v1/songs_controller.rb
module Api
  module V1
    class SongsController < ApplicationController

    def feedback
      params.permit!
      feedback = SongFeedback.new(params[:feedback])
      feedback.save
      if feedback.valid?
        render json: { message: "Thanks! We will review this song soon!" }, status: :ok
      else
        render json: { message: "Sorry! Unable to submit your feedback." }, status: :bad_request
      end
    end

    def archive_song
      if request.xhr?
        @song=Song.find(params[:id])
        begin
          client = Dropbox::API::Client.new(:token  => AdminUser.first.dropbox_access_token, :secret =>  AdminUser.first.dropbox_secret_token)
          if !client.ls '/archive'
            client.mkdir 'archive'
          end
          file = client.find @song.path
          file.move "/archive/#{@song.file_name}"
          @song.update_attributes(before_archive_path: @song.path, path:"archive/#{@song.file_name}", active: false)
        rescue Exception => e
          puts "Some error"+e
        end
      else
        SongArchive.perform_async(params[:id])
        redirect_to admin_songs_path
      end
    end

    def unarchive_song
      if request.xhr?
        @song=Song.find(params[:id])
        begin
          client = Dropbox::API::Client.new(:token  => AdminUser.first.dropbox_access_token, :secret =>  AdminUser.first.dropbox_secret_token)
          if !client.ls '/archive'
            client.mkdir 'archive'
          end
          file = client.find @song.path
          file.move @song.before_archive_path
          @song.update_attributes(path:@song.before_archive_path, active: true, before_archive_path: nil)
        rescue Exception => e
          puts "Some Error"
        end
      else
        SongUnarchive.perform_async(params[:id])
        redirect_to admin_songs_path
      end
    end

    def admin_active_inactive_song
      @song=Song.find(params[:id])
      if @song.active
        @song.update_attribute :active, false
      else
        @song.update_attribute :active, true
      end
    end

    def admin_update_song
      @song=Song.find(params[:id])
      if params[:title].present?
        @song.update_attribute :title, params[:title]
      elsif params[:artist].present?
        @song.update_attribute :artist, params[:artist]
      elsif params[:year].present?
        @song.update_attribute :year, params[:year]
      elsif params[:active].present?
        @song.update_attribute :active, params[:active]
      elsif params[:genres].present?
        @song.genre_songs.destroy_all
        if params[:genres].last != "None"
          params[:genres].each do |genre|
            genre_id = Genre.find_by_name(genre).id
            @song.genre_songs.new(genre_id: genre_id).save
          end
        end
        render :json => {"id" => @song.id, "genre_names" => @song.genres.map(&:name).join(', ')}
        return true
      end
      SongUpdate.perform_async(@song.id)
      render :json => @song
    end

    def admin_play_song
      @song=Song.find(params[:id])
      render :json => {"playing_url" => @song.streaming_url}
    end

    def get_expanded_data
      @song= Song.find(params[:id])
      render :json => {"single_datas" => @song.single_datas, "double_datas" => @song.double_datas, "question_answer_datas" => @song.question_answer_datas}
    end

    def download_song_data
      SongCsvDownloadWorker.perform_async
      redirect_to admin_songs_path
      flash[:success] = "CSV uploaded to S3"
    end

    def download_playlist_song_data
      require "csv"
      respond_to do |format|
        format.html
        format.xls { send_data Song.playlist_song_csv(col_sep: "\t"), filename: "all_playlist_songs_#{Date.today}.csv" }
      end
    end

    def download_songs_in_playlist
      playlist_id = params["id"]
      playlist_name = Playlist.find(playlist_id).name
      require "csv"
      respond_to do |format|
        format.html
        format.xls { send_data Song.song_in_playlist_csv(col_sep: "\t", id: playlist_id), filename: "songs_in_playlist_#{playlist_name}.csv" }
      end
    end

    def admin_update_song_custom_data
      @song = Song.find(params[:id])
      if params[:single_data].present?
        @song.single_datas.destroy_all
        params[:single_data].each do |single_data|
          @song.single_datas.create(single_custom_data: single_data) if single_data.present?
        end
      elsif params[:double_data].present?
        @song.double_datas.destroy_all
        params[:double_data].each do |key,value|
          @song.double_datas.create(double_custom_data1: key, double_custom_data2: value) if key.present?
        end
      elsif params[:question_data].present?
        @song.question_answer_datas.destroy_all
        params[:question_data].each do |key,value|
          @song.question_answer_datas.create(question: key, answer: value) if key.present?
        end
      end
      render :json => @song
    end

    private

    def resource
      Round.find(params[:round_id]).game.rounds.last
    end

    def authenticate_users
      if current_admin_user.present?
        :authenticate_admin_user!
      elsif current_account.present?
        :authenticate_account!
      end
      end
    end
  end
end

app/views/admin/songs/_download_playlist_song_data.html.haml
Tip: Download all the songs from listed playlist
=button_to('Upload Playlist Song Data to CSV', admin_download_playlist_song_data_path(format: 'xls'), disable_with: "Uploading...")
%div{:style => 'margin:1rem'}
=button_to('Download CSV', 'https://s3.amazonaws.com/csv-mayhem/all_playlist_songs.csv',method:'get', disable_with: "Downloading...")

%div{:style => 'margin:1rem 0;border:1px solid #d4d4d4'}

%form
  %h5 Upload Playlist CSV here
  %input{:id => 'PlaylistCsv',:accept => ".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel", :name => "csv", :type => "file" }
  %div{:style => 'margin:1rem 0'}
%button{:style => "border-radius: 200px;padding: 7px 16px 6px;background: #133352;border: solid 1px #686868;color: #efefef;cursor: pointer;", :onClick => "uploadCsv()" } Upload Csv


:javascript
  function uploadCsv(){
    var files = document.getElementById('PlaylistCsv').files;
    if (!files.length) {
      return alert('Please choose a file to upload first.');
    }
    var file = files[0];
    var fileName = file.name;
    var fdata = new FormData()
    fdata.append("data", file)
    $.ajax({
      method: "POST",
      url: "/admin/upload_playlist_csv",
      data: fdata,
      contentType: false,
      processData: false,
      success: function(data){
        alert("PLAYLIST CSV UPLOADED!!!")
        location.reload()
      }
    });
    }

app/views/admin/songs/_download_song_data.html.haml
Tip: Download all the songs data
=button_to('Upload Song Data to AWS', admin_download_song_data_path(format: 'xls'), disable_with: "Uploading...")
%div{:style => 'margin:1rem 0'}
=button_to('Download CSV', 'https://s3.amazonaws.com/csv-mayhem/songs_data.csv',method:'get', disable_with: "Downloading...")
%div{:style => 'margin:1rem 0;border:1px solid #d4d4d4'}

%form
  %h5 Upload Song CSV here
  %input{:id => 'SongCsv',:accept => ".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel", :name => "csv", :type => "file" }
  %div{:style => 'margin:1rem 0'}
%button{:style => "border-radius: 200px;padding: 7px 16px 6px;background: #133352;border: solid 1px #686868;color: #efefef;cursor: pointer;", :onClick => "uploadCsv()" } Upload Csv


:javascript
  function uploadCsv(){
    var files = document.getElementById('SongCsv').files;
    if (!files.length) {
      return alert('Please choose a file to upload first.');
    }
    var file = files[0];
    var fileName = file.name;
    var fdata = new FormData()
    fdata.append("data", file)
    $.ajax({
      method: "POST",
      url: "/admin/upload_csv",
      data: fdata,
      text: "Song",
      contentType: false,
      processData: false,
      success: function(data){
        alert("SONG CSV UPLOADED!!!")
        location.reload()
      }
    });
    }

app/views/admin/songs/_download_songs_in_playlist.html.haml
Tip: Download all the songs listed in playlist
=button_to('Download Songs in Playlist', admin_download_songs_in_playlist_path(format: 'xls', id: params[:id]), disable_with: "Downloading...")

app/views/admin/songs/_play_song.html.erb
<%= link_to "Play", '#', class:'play-song mm-button success'%>
<%= hidden_field_tag "song[id]", song.id %>

app/views/admin/songs/add_to_playlist.js.erb
$('.flashes').remove();
$('.title_bar').after($('<%= raw(flash_notification("Added Song to Current Playlist: #{link_to @playlist.name, [:admin, @playlist]}")) %>'));